/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminComponent: typeof import('./src/components/mainContent/AdminComponent.vue')['default']
    AdminMenu: typeof import('./src/components/menu/AdminMenu.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CartComponent: typeof import('./src/components/mainContent/CartComponent.vue')['default']
    CartMenu: typeof import('./src/components/menu/CartMenu.vue')['default']
    Categories: typeof import('./src/components/adminsContent/Categories.vue')['default']
    CategoriesMenu: typeof import('./src/components/forMenu/CategoriesMenu.vue')['default']
    CategoriesSubmenu: typeof import('./src/components/forMenu/CategoriesSubmenu.vue')['default']
    CreateCategories: typeof import('./src/components/adminsContent/CreateCategories.vue')['default']
    EmptyAdmins: typeof import('./src/components/adminsContent/EmptyAdmins.vue')['default']
    ErrorModal: typeof import('./src/components/mainLayout/ErrorModal.vue')['default']
    Events: typeof import('./src/components/adminsContent/Events.vue')['default']
    Footer: typeof import('./src/components/mainLayout/Footer.vue')['default']
    GetCategories: typeof import('./src/components/adminsContent/GetCategories.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeComponent: typeof import('./src/components/mainContent/HomeComponent.vue')['default']
    HomeMenu: typeof import('./src/components/menu/HomeMenu.vue')['default']
    LoginComponent: typeof import('./src/components/mainContent/LoginComponent.vue')['default']
    LoginMenu: typeof import('./src/components/menu/LoginMenu.vue')['default']
    MainContent: typeof import('./src/components/mainLayout/MainContent.vue')['default']
    NavBar: typeof import('./src/components/mainLayout/NavBar.vue')['default']
    NotFoundComponent: typeof import('./src/components/mainContent/NotFoundComponent.vue')['default']
    NotFoundMenu: typeof import('./src/components/menu/NotFoundMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
